### ISSUE TITLE
Errow when installing hic_qc

### ISSUE THREAD

**Issue by freelongsong** [phasegenomics/hic_qc#48]
Hi,

I followed the instructions to install hic_qc on HPC with my own account. The error message is as following.  I know nothing about Python. Could anyone help me solve this?

Thanks!

(hic_qc)
/home/lson1234/tools/hic_qc $ python setup.py install --user
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    version=versioneer.get_version(),
  File "/home/lson1234/tools/hic_qc/versioneer.py", li                                                                                                             ne 1480, in get_version
    return get_versions()["version"]
  File "/home/lson1234/tools/hic_qc/versioneer.py", li                                                                                                             ne 1453, in get_versions
    pieces = from_vcs_f(cfg.tag_prefix, root, verbose)
  File "/home/lson1234/tools/hic_qc/versioneer.py", li                                                                                                             ne 1110, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string, a bytes-like object or a number, not                                                                                                              'NoneType'

**Comment by shawnpg** [comment]
Hi,

Thanks for reporting this issue. It is likely this has something to do with the environment, and that we will be able to detect and recover from this issue. The failure appears to be in versioneer.py, which is redistributed with hic_qc. It might be a problem with git not being installed on the machine from how it's failing. Do you know if git is installed on the HPC?

Thanks!

**Comment by maximilianpress** [comment]
It might be helpful to know whether you previously attempted to install the dependencies using pip or conda as outlined in the Readme. 

Which of these two did you try before running `setup.py`?
