### ISSUE TITLE
qc_repo_path not defined in write_pdf_report()

### ISSUE THREAD

**Issue by chuseq** [phasegenomics/hic_qc#54]
Hi,

Installed the package, along with its requirements with conda. When running the following command line:
$ hic_qc.py -b KO61_aligned.bam -r -o K061_output

At the end we get an error about qc_repo_path not defined, and no html nor pdf file is generated.

```
    QC.write_pdf_report()
  File "/usr/local/hic_qc/hic_qc.py", line 1105, in write_pdf_report
    qc_repo_path)
NameError: global name 'qc_repo_path' is not defined
```

Thanks in advance for your help.

**Comment by chuseq** [comment]
Hi again,
So i replaced line 1105 with template_path instead of qc_repo_path and it worked. 

Before:
`    qc_repo_path)`
After:
`    tempalte_path)`

**Comment by bnelsj** [comment]
Hi @chuseq , thanks for reporting! This issue will be resolved once the PR is approved.
