### ISSUE TITLE
The --make_report flag doesn't get used

### ISSUE THREAD

**Issue by aakashsur** [phasegenomics/hic_qc#64]
https://github.com/phasegenomics/hic_qc/blob/219b0aa9f841aa18ef7d4fbee36f52666ae632b3/hic_qc.py#L1101

I noticed that the PDF report is generated by default, and the flag never gets used even though it has a default value of false according to its help description. 

https://github.com/phasegenomics/hic_qc/blob/219b0aa9f841aa18ef7d4fbee36f52666ae632b3/hic_qc.py#L1153

I personally think the report is great, and should probably be made by default, so I guess the flag could do the opposite if you guys wanted.

**Comment by bnelsj** [comment]
Hi @aakashsur , #68 should address this. Let me know if you have any comments on the details.
