### ISSUE TITLE
HiCQC' object has no attribute 'ref_assembly

### ISSUE THREAD

**Issue by ardy20** [phasegenomics/hic_qc#72]
Hello

I aligned my HiC data on reference using Bowties. Then I used hic-qc but I get the following error:

(base) user@fl017:.../project/qaafi-cnafs/bowtie2-master> hic_qc.py -b align.bam -n 1750306
[hic_qc - 2022-02-14 16:55:44,615] parsing the first 1750306 read pairs in bam file align.bam to QC Hi-C library quality
Traceback (most recent call last):
  File "/sw/QFAB/miniconda3/envs/hic_qc_20211115/bin/hic_qc.py", line 1151, in <module>
    QC.stringify_stats()
  File "/sw/QFAB/miniconda3/envs/hic_qc_20211115/bin/hic_qc.py", line 870, in stringify_stats
    'ref_assembly': (self.ref_assembly, '{}'),
AttributeError: 'HiCQC' object has no attribute 'ref_assembly'

**Comment by Astahlke** [comment]
Hello! 

I just got the same error using a different mapping pipeline than I normally use which doesn't fail this way. Must be related to the way the bam is generated? 
 
```
$ python hic_qc.py -b phasehic.samblasted.samfiltered.bam -o phase
[hic_qc - 2022-08-05 16:54:40,739] parsing the first 1000000 read pairs in bam file dedup_files/hic_reads.dedup.readsort.bam to QC Hi-C library quality
[E::idx_find_and_load] Could not retrieve index file for 'dedup_files/hic_reads.dedup.readsort.bam'
Traceback (most recent call last):
  File "hic_qc.py", line 1151, in <module>
    QC.stringify_stats()
  File "hic_qc.py", line 870, in stringify_stats
    'ref_assembly': (self.ref_assembly, '{}'),
AttributeError: 'HiCQC' object has no attribute 'ref_assembly'
```

In this case, I used the Arima mapping pipeline https://github.com/ArimaGenomics/mapping_pipeline then sorted the resulting bam by read name with `samtools sort -n `. Lots of output is generated but the full report cannot complete. 

I installed using conda. 

Thanks!

Amanda

**Comment by dimovskik** [comment]
Hello,

I have also encountered the above problem:

```
[hic_qc - 2022-09-07 11:58:45,819] parsing the first 1257280 read pairs in bam file /home/dimovski/HiC/2019-28929-M4.bam to QC Hi-C library quality
Traceback (most recent call last):
  File "hic_qc.py", line 1151, in <module>
    QC.stringify_stats()
  File "hic_qc.py", line 870, in stringify_stats
    'ref_assembly': (self.ref_assembly, '{}'),
AttributeError: 'HiCQC' object has no attribute 'ref_assembly'

```
Am i doing something wrong?

Thanks!
K

**Comment by SaiReddy-A** [comment]
It worked for me after commenting out lines 870-872 of `hic_qc.py`
> #'ref_assembly': (self.ref_assembly, '{}'),
#'fwd_hic_reads': (self.fwd_hic_reads, '{}'),
#'rev_hic_reads': (self.rev_hic_reads, '{}'),

And by removing lines with `{ref_assembly}` ` {fwd_hic_reads}` `{rev_hic_reads}` from `collateral/HiC_QC_report_template.md` file
